### ISSUE TITLE
Replace use of console

### ISSUE THREAD

**Issue by digimangos** [igwejk/action-steady-step#1]
Hi @igwejk 

Would it be better to replace the [following](https://github.com/igwejk/action-steady-step/blob/586254775e768ff7458d2643cbdd3cd154d8defe/index.js#L29,30):
```javascript
        console.log("stdout:", stdout);
        console.error("stderr:", stderr);
```

with

```javascript
        core.info(`stdout: ${stdout}`);
        core.error(`stderr: ${stderr}`);
```

**Comment by igwejk** [comment]
Fixed, thanks @digimangos
